name: fslapp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
  

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run lint
      - run: npm install -g prettier
      - run: npm run prettier
      - run: npm run test
      - run: npm run build

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: naska8701/fsl-project
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}