name: fslapp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - run: npm run install
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test
      - run: npm run build